#!/usr/bin/env python3

"""
Script for uploading an entire folder

Usage: update_folder FOLDER DESTINATION

  FOLDER       the folder to be uploaded, absolute or relative path
  DESTINATION  the gss destination, which must exist before  (e.g. it4i_anselm://
               or it4i_salomon://destination_folder/)

  username, project and password must be specified in environment variables
    CFG_USERNAME, CFG_PASSWORD, CFG_PROJECT

"""

import clfpy as cf
import os
import os.path
import sys

auth_url = "https://api.hetcomp.org/authManager/AuthManager?wsdl"
gss_url = "https://api.hetcomp.org/gss-0.1/FileUtilities?wsdl"

def main():

    if not os.path.isdir(os.path.abspath(sys.argv[1])):
        print("Folder {} does not exists.".format(sys.argv[1]))
        return

    try:
        username = os.environ['CFG_USERNAME']
        password = os.environ['CFG_PASSWORD']
        project = os.environ['CFG_PROJECT']
    except KeyError:
        print("CFG_USERNAME, CFG_PASSWORD and CFG_PROJECT environment variables \
are not defined.")
        username = input("Please enter the username: ")
        password = input("Please enter the password: ")
        project = input("Please enter the project: ")

    print("Obtaining session token ...")
    auth = cf.AuthClient(auth_url)
    session_token = auth.get_session_token(username, project, password)
    if "Server raised fault" in str(auth.get_token_info(session_token)):
        print("Autentication failed")
        return
    print("Autentication complete")

    dirlist = [os.path.join(root,dir) for root,dirs,__ in os.walk(os.path.abspath(sys.argv[1]))
            for dir in dirs]
    filelist = [os.path.join(root,file) for root,__,files in os.walk(os.path.abspath(sys.argv[1]))
            for file in files]
    dirlist.append(os.path.abspath(sys.argv[1]))

    old_base = os.path.dirname(os.path.abspath(sys.argv[1])) + '/'
    new_base = sys.argv[2]
    if new_base[-1] is not "/":
        new_base += "/"

    gss_dirlist =  [d.replace(old_base,new_base) for d in dirlist]
    gss_filedict = { f : f.replace(old_base,new_base) for f in filelist}
    gss_dirlist.sort()

    gss = cf.GssClient(gss_url)
    print("Creating remote folders...")
    for gss_dir in gss_dirlist:
        gss.create_folder(gss_dir, session_token)
    print("Uploading files...")
    for local_file, gss_file in gss_filedict.items():
        print(gss.upload(gss_file, session_token, local_file))

if __name__ == "__main__":
    main()
